<a href="https://colab.research.google.com/github/kartik2006-del/efficient-finetuning-lora/blob/main/lora_finetuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##  Target-module comparison

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
!pip uninstall torchao

WARNING: Skipping torchao as it is not installed.

In [3]:
from datasets import load_dataset, Dataset

dataset = load_dataset(
    "yahma/alpaca-cleaned",
    split="train"
)

df = dataset.to_pandas()
df = df.drop_duplicates()

dataset = Dataset.from_pandas(
    df,
    preserve_index=False
)

train_test = dataset.train_test_split(
    test_size=0.20,
    seed=42
)

train_data = train_test["train"]
temp_data = train_test["test"]

validation_test = temp_data.train_test_split(
    test_size=0.50,
    seed=42
)

validation_data = validation_test["train"]
test_data = validation_test["test"]

print("Train:", len(train_data))
print("Validation:", len(validation_data))
print("Test:", len(test_data))

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Train: 41404
Validation: 5176
Test: 5176

In [4]:
from transformers import AutoTokenizer, DataCollatorForLanguageModeling

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token


def format_chat(example):
    if example["input"].strip():
        user_content = (
            example["instruction"]
            + "\n\nInput:\n"
            + example["input"]
        )
    else:
        user_content = example["instruction"]

    messages = [
        {"role": "user", "content": user_content},
        {"role": "assistant", "content": example["output"]}
    ]

    return {
        "text": tokenizer.apply_chat_template(
            messages,
            tokenize=False
        )
    }


def tokenize_function(example):
    return tokenizer(
        example["text"],
        truncation=True,
        max_length=512,
        padding="max_length"
    )


validation_test_data = validation_data.select(range(100))

validation_test_data = validation_test_data.map(
    format_chat
)

validation_test_data = validation_test_data.map(
    tokenize_function,
    batched=True,
    remove_columns=validation_test_data.column_names
)


data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

print("Setup restored successfully.")

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Setup restored successfully.

In [5]:
full_ft_test_data = train_data.select(range(100))

full_ft_test_data = full_ft_test_data.map(
    format_chat
)

full_ft_test_data = full_ft_test_data.map(
    tokenize_function,
    batched=True,
    remove_columns=full_ft_test_data.column_names
)

print("Training examples:", len(full_ft_test_data))

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Training examples: 100

In [6]:
!pip install -U "bitsandbytes>=0.46.1"

Requirement already satisfied: bitsandbytes>=0.46.1 in /usr/local/lib/python3.13/dist-packages (0.50.2)
Requirement already satisfied: torch<3,>=2.4 in /usr/local/lib/python3.13/dist-packages (from bitsandbytes>=0.46.1) (2.11.0+cu128)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.13/dist-packages (from bitsandbytes>=0.46.1) (2.1.3)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.13/dist-packages (from bitsandbytes>=0.46.1) (26.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.32.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (2025.12.0)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.13/dist-packages (from torch<3,>=2.4->bitsandbytes>=0.46.1) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.13/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch<3,>=2.4->bitsandbytes>=0.46.1) (12.8.90)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.13/dist-packages (from cuda-bindings<13,>=12.9.4->torch<3,>=2.4->bitsandbytes>=0.46.1) (1.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch<3,>=2.4->bitsandbytes>=0.46.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch<3,>=2.4->bitsandbytes>=0.46.1) (3.0.3)

In [7]:
import torch
from transformers import (
    AutoModelForCausalLM,
    BitsAndBytesConfig
)

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

qlora_base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto"
)

print("QLoRA base model loaded successfully.")
print("Model dtype:", qlora_base_model.dtype)

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

QLoRA base model loaded successfully.
Model dtype: torch.bfloat16

In [8]:
from peft import (
    prepare_model_for_kbit_training,
    LoraConfig,
    get_peft_model
)

qlora_base_model = prepare_model_for_kbit_training(
    qlora_base_model
)

qlora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
    task_type="CAUSAL_LM"
)

qlora_model = get_peft_model(
    qlora_base_model,
    qlora_config
)

qlora_model.print_trainable_parameters()

trainable params: 1,081,344 || all params: 495,114,112 || trainable%: 0.2184

In [9]:
import time
import torch
from transformers import TrainingArguments, Trainer

torch.cuda.empty_cache()
torch.cuda.reset_peak_memory_stats()

qlora_model.config.use_cache = False
qlora_model.train()

training_args = TrainingArguments(
    output_dir="./outputs/qlora_test",
    max_steps=20,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    fp16=True,
    logging_steps=5,
    save_strategy="no",
    report_to="none"
)

trainer = Trainer(
    model=qlora_model,
    args=training_args,
    train_dataset=full_ft_test_data,
    eval_dataset=validation_test_data,
    data_collator=data_collator
)

start_time = time.time()

train_output = trainer.train()

training_time = time.time() - start_time

peak_memory_gb = (
    torch.cuda.max_memory_allocated() / (1024 ** 3)
)

eval_output = trainer.evaluate()

eval_loss = eval_output["eval_loss"]

print("\n===== QLoRA Results =====")
print(f"Training time: {training_time:.2f} sec")
print(f"Peak GPU memory: {peak_memory_gb:.2f} GB")
print(f"Train loss: {train_output.training_loss:.4f}")
print(f"Eval loss: {eval_loss:.4f}")

/usr/local/lib/python3.13/dist-packages/torch/_dynamo/eval_frame.py:1263: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. Starting in PyTorch 2.9, calling checkpoint without use_reentrant will raise an exception. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  return fn(*args, **kwargs)

===== QLoRA Results =====
Training time: 12.30 sec
Peak GPU memory: 1.88 GB
Train loss: 2.0404
Eval loss: 1.6260